package de.mari.types.social.socials

import de.mari.types.social.Social

// DO NOT EDIT THIS FILE HERE
// DO NOT EDIT THIS FILE HERE
class Reddit(username: String) : Social("Reddit", "https://reddit.com/u/$username")
